# Project information
site_name: The Adventures of Ravenlost
site_author: Angela Bartz
site_url: https://abartzgit.github.io/ravenlost/

# Copyright
copyright: Copyright &copy; 2026 Angela Bartz

# Add extensions for Markdown processing, including support for attributes, Markdown in HTML, and admonitions.
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - toc:
      toc_depth: 2

# Configuration
theme: 
  name: material
  logo: images/logo.png
  favicon: images/favicon.png

  # Auto-expand the left navigation and include previous and next navigation in the footer.
  features: 
    - navigation.footer
  
  # Set the color palette for light and dark mode, and include a toggle to switch between them.
  palette:
    # Light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Extras
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/users/1125538089457160232
    - icon: fontawesome/brands/github
      link: https://github.com/ABartzGit/ravenlost
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/angela-bartz/
      
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list

# Site navigation
nav: 
  - Level 1:
    - Four strangers in the Mists: chapters/chapter01/chapter-01-the-black-lantern-inn.md
  - Level 2:
    - The Shadows of Crawford: chapters/chapter02/chapter-02-crawford-battles.md
    - The Battle of Crawford Manor: chapters/chapter02/chapter-02-crawford-manor-battle.md
  - Level 3:
    - Shaking things up in Waterford: chapters/chapter03/chapter-03-waterford-battles.md
    - Home is where the horrors are: chapters/chapter03/chapter-03-home-is-where-the-horrors-are.md
  - Notes:
    - Level 1:
       - Bia's notes - Four strangers in the Mists: notes/chapter01/chapter-01-session-notes.md
    - Level 2:
      - Bia's notes - The Shadows of Crawford: notes/chapter02/chapter-02-session-notes-01.md
      - Bia's notes - The Battle of Crawford Manor: notes/chapter02/chapter-02-session-notes-02.md
    - Level 3:
      - Bia's notes - Shaking things up in Waterford: notes/chapter03/chapter-03-session-notes-01.md
      - Bia's notes - Home is where the horrors are: notes/chapter03/chapter-03-session-notes-02.md
  - Bia's character sheets: character-sheets/bia-character-sheets.md

