# Project information
site_name: The Adventures of Ravenlost
site_author: Angela Bartz
site_url: https://abartzgit.github.io/ravenlost/

# Copyright
copyright: Copyright &copy; 2026 Angela Bartz

# Add extensions for Markdown processing, including support for attributes, Markdown in HTML, and admonitions.
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - toc:
      toc_depth: 2

# Configuration
theme: 
  name: material
  logo: images/logo.png
  favicon: images/favicon.png

  # Auto-expand the left navigation and include previous and next navigation in the footer.
  features: 
    - navigation.expand
    - navigation.footer
  
  # Set the color palette for light and dark mode, and include a toggle to switch between them.
  palette:
    # Light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Extras
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/users/1125538089457160232
    - icon: fontawesome/brands/github
      link: https://github.com/ABartzGit/ravenlost
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/angela-bartz/
      
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list

# Site navigation
nav: 
  - Chapter 1:
    - The Black Lantern Inn: chapter01/chapter-01-the-black-lantern-inn.md
    - Notes:
      - Bia's Chapter 1 notes: chapter01/chapter-01-dnd-notes.md
  - Chapter 2:
    - The Shadows of Crawford: chapter02/chapter-02-crawford-battles.md
    - Notes:
      - Bia's notes for Crawford: chapter02/chapter-02-dnd-crawford-notes.md
  - Character sheets: 
    - Bia's character sheets: character-sheets/bia-character-sheets.md

